# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.IntegerField()),
                ('ava', models.BooleanField(default=True)),
                ('time_updated', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
